name: Publish nuget

on:
  push:
    branches:
      - gh-action

jobs:
  pack-publish-nuget:
    runs-on: ubuntu-latest
    name: Pack and publish to nuget
    steps:
      - uses: actions/checkout@v3
      - name: dotnet pack
        run: dotnet pack -c release
      - name: dotnet publish
        run: dotnet nuget push packages/ -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
